- name: Installing golang
  ansible.builtin.dnf:
    name: golang
    state: present

- name: download the dependencies & build the software.
  ansible.builtin.shell: go mod init dispatch; go get; go build
  args:
    chdir: /app